### PR TITLE
Review content to make sure it matches the latest versions

### PR DESCRIPTION
**Pull request by pablo-de-andres**

### CODE REVIEW

**Comment by pablo-de-andres** [comment]
@kysrpex I have done a general read and dealt with most of the warnings being shown in the build process.
The remaining ones come from the api ref, so I do not think they should be tackled here (but in the actual docstrings). I briefly tried to silent them, but did not manage.

I would hand over to you now, ping me if you need anything

**Comment by pablo-de-andres** [comment]
Regarding `black` and `isort`, I run into some issues with pre-commit in another project, this is the configuration that worked in the end:
```yml

    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
            args:
                - --line-length=79

    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
            args:
                - --profile=black
                - --filter-files
                - --line-length=79
```
Leaving it here so we can apply it next week :)

**Comment by pablo-de-andres** [comment]
@kysrpex [this](https://github.com/simphony/docs/pull/213#issuecomment-1179148832) has not been applied, has it?

Maybe we can just push the change to `dev`

**Comment by kysrpex** [comment]
> @kysrpex [this](https://github.com/simphony/docs/pull/213#issuecomment-1179148832) has not been applied, has it?
> 
> Maybe we can just push the change to `dev`

When you commented I was going to make a new PR, but it seems that [it is already on dev](https://github.com/simphony/docs/blob/2799b19dbefdae1827ccd34f1867419b13f4f472/.pre-commit-config.yaml#L22).

**Comment by pablo-de-andres** [comment]
I seem to remember that syntax did not work as it should for me. That is why I suggested the alternative above.

**Comment by kysrpex** [comment]
> I seem to remember that syntax did not work as it should for me. That is why I suggested the alternative above.

Then if you remember what was not working we make a PR. I do not remember :sweat_smile: .

**Pull request merged**
