### PR TITLE
Create dockerfile for local installation with hot-reload

### LINKED ISSUE #88: Create dockerfile

### PR DESCRIPTION
**Pull request by yoavnash**
Closes #88, #100

### CODE REVIEW

**Comment by kysrpex** [comment]
A very dumb question: the point of adding this dockerfile is to be able to build the docs locally without having to install all the dependencies, right?

**Comment by yoavnash** [comment]
Indeed.

**Comment by yoavnash** [comment]
A new commit has been added that enables hot reload

**Comment by pablo-de-andres** [comment]
I usually find it a good practice to add at the end of the Dockerfile a couple of comments explaining how to build and run an image, especially when custom arguments are required

**Comment by yoavnash** [comment]
Good idea. I added the following lines to the end of the file:

```dockerfile
# Build:
# $ docker build -t simphony-docs .

# Run:
# $ docker run -v $PWD:/app -p 5500:5500 simphony-docs
```

**Pull request closed without merging**
