### PR TITLE
Add Dockerfile with Hot-Reload

### LINKED ISSUE #88: Create dockerfile

### PR DESCRIPTION
**Pull request by yoavnash**
Closes #88, #100

A new pull request due to a branching problem in the old one (see https://github.com/simphony/docs/pull/89).

### CODE REVIEW

**Comment by kysrpex** [comment]
This is great! It is working and exposing the documentation on http://127.0.0.1:5500/. This will help a lot reviewing the changes to the docs.

**Comment by yoavnash** [comment]
@kysrpex The readme file is now updated. You may want to have a look before we merge.

**Comment by yoavnash** [comment]
Everything works for me.
@pablo-de-andres I made some small changes in the docs on top of yours. Please see that you're fine with them. If so, I think you can simply merge.

**Review by pablo-de-andres — APPROVED** [review]
Looks good!

**Pull request merged**
